# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Updated for Railway deployment with custom embedding support
FROM python:3.12-slim

# set working directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copy project files
COPY . /app

# Install pip dependencies
RUN python -m pip install --upgrade pip && \
    pip install .

# Set environment variables for Railway
ENV PYTHONUNBUFFERED=1
ENV PORT=8080

# Expose port (Railway will set this automatically)
EXPOSE 8080

# Health check for Railway monitoring
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \
    CMD python -c "import sys; sys.exit(0)" || exit 1

# Command to run MCP server
CMD ["chroma-mcp"]
